version: 2
registries:
  npm-greatminds-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.DEPENDABOT_GITHUB_TOKEN }}
    replaces-base: true
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
      - npm-greatminds1-github
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:30'
      timezone: 'America/New_York'
    commit-message:
      prefix: 'auto-upgrade'
