name: Deploy App to Railway

on:
  workflow_call:
    inputs:
        env:
            required: true
            type: string
        image:
            required: true
            type: string
        image_tag:
            required: true
            type: string
    secrets:
        RAILWAY_TOKEN:
            required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy image to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo "Deploying Docker image: ${{ inputs.image }}:${{ inputs.image_tag }}"
          railway up -- \
          --project ${{ vars.RAIL_PROJECT_ID }} \
          --service docker \
          --detach \
          --env ${{ inputs.env }} \
          --build-env IMAGE=${{ inputs.image }}:${{ inputs.image_tag }}

      - name: Done
        run: echo "Deployment completed successfully 🎉"
