---
  name: 'Call Deploy Sourcemaps'
  on:
    workflow_dispatch:
      inputs:
        environment:
          type: choice
          description: environment to deploy
          options:
            - dev
            - test
  
  jobs:
    deploy-sourcemaps:
      uses: ./.github/workflows/deploy-sourcemaps.yaml
      with:
        env: ${{ inputs.environment }}
        install_cmd: 'npm install'
        build_cmd: 'npm run build:with-sourcemaps'
      secrets:
        NEW_RELIC_API_USER_KEY: ${{ secrets.NEW_RELIC_API_USER_KEY }}
  
